Power Query Transformation Steps — EV Dashboard Project
========================================================

Source: electric_vehicles_spec_2025.csv

Steps:

1. Promote Headers
- Use "Use First Row as Headers" to ensure proper column names.

2. Trim Text Fields
- Apply Transform → Format → Trim to:
  brand, model, battery_type, fast_charge_port, drivetrain, segment, car_body_type, source_url

3. Replace Empty Strings with Null
- Replace "" with null for both text and numeric columns.

4. Change Column Types
- Decimal Number:
  top_speed_kmh, battery_capacity_kWh, torque_nm, efficiency_wh_per_km, acceleration_0_100_s, fast_charging_power_kw_dc, towing_capacity_kg
- Whole Number:
  range_km, cargo_volume_l, seats, length_mm, width_mm, height_mm, number_of_cells
- Text:
  brand, model, drivetrain, segment, car_body_type, battery_type, fast_charge_port, source_url

5. Fix Non-Numeric Artifacts
- Replace "—", "n/a", "-" with null in columns like cargo_volume_l and fast_charging_power_kw_dc
- Then convert to numeric type

6. Remove Rows Without Brand or Model
- Filter out rows where brand or model is null

7. Remove Duplicates
- Use Remove Duplicates on [brand, model]

8. Standardize Categories
- Replace inconsistent values:
  - JC - Medium → C - Medium
  - Drivetrain values → AWD, FWD, RWD

9. Rename Query
- Rename to: EVs

10. Close & Apply

Sample M Code (auto-generated by Power BI):
```m
let
  Source = Csv.Document(File.Contents("..."),[Delimiter=",", Columns=22, Encoding=1252, QuoteStyle=QuoteStyle.Csv]),
  PromotedHeaders = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
  Trimmed = Table.TransformColumns(PromotedHeaders, {
      {"brand", Text.Trim}, {"model", Text.Trim}, {"battery_type", Text.Trim}, {"fast_charge_port", Text.Trim},
      {"drivetrain", Text.Trim}, {"segment", Text.Trim}, {"car_body_type", Text.Trim}
  }),
  ReplaceDash = Table.ReplaceValue(Trimmed,"—",null,Replacer.ReplaceValue,{"cargo_volume_l","fast_charging_power_kw_dc"}),
  ChangedTypes = Table.TransformColumnTypes(ReplaceDash,{
      {"top_speed_kmh", type number}, {"battery_capacity_kWh", type number}, {"number_of_cells", Int64.Type},
      {"torque_nm", type number}, {"efficiency_wh_per_km", type number}, {"range_km", Int64.Type},
      {"acceleration_0_100_s", type number}, {"fast_charging_power_kw_dc", type number},
      {"towing_capacity_kg", type number}, {"cargo_volume_l", Int64.Type}, {"seats", Int64.Type},
      {"length_mm", Int64.Type}, {"width_mm", Int64.Type}, {"height_mm", Int64.Type}
  }),
  RemoveBlank = Table.SelectRows(ChangedTypes, each [brand] <> null and [model] <> null),
  RemoveDuplicates = Table.Distinct(RemoveBlank, {"brand","model"})
in
  RemoveDuplicates
